name: Build and Publish image to GHCR
on:
  push:
    branches:
      - main

jobs:
    publish_images:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - name: Build and Push Image to GHCR
              env:
                # Using the built in token instead of a Personal Access Token
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                # Using the repository owner as part of the image tagging process
                OWNER="${{ github.repository_owner }}"
                # Converting to lowercase to comply with Docker image naming conventions
                OWNER="${OWNER,,}"
                # Defining image name to ensure consistency and a DRY approach
                IMAGE_NAME="ghcr.io/$OWNER/swapi-script:latest"
                # Making sure to login using stdin to avoid leaking secrets in logs
                echo "$GH_TOKEN" | docker login ghcr.io -u $OWNER --password-stdin
                docker build . -t $IMAGE_NAME
                docker push $IMAGE_NAME
